### ISSUE TITLE
Needs to delegate events

### ISSUE THREAD

**Issue by ryanflorence** [kevinvaldek/mootools-ujs#2]
Dynamically created elements don't respond to this driver.

**Comment by kevinvaldek** [comment]
Yes, events are only applied on domready to document.body. If you add any elements dynamically, you can apply all events on a specified element again by calling rails.applyEvents($('container_element')).

For instance when you have updated contents of an element by an ajax request, take a look at this gist: http://gist.github.com/408582

Thanks for reporting this, as it's not obvious in the README, but I'll add it now.

**Comment by elado** [comment]
Why not just using

`el.addEvent(action+':relay('+selector+')', callback);`

in the apply function? (With MooTools More Event Delegation as a dependency)

This plugin should be transparent to the application's code.

**Comment by kevinvaldek** [comment]
That would be a better solution, but I'm not sure that introducing a dependency is the way to go.

Another option would be to use delegation in case the relay pseudo is defined. That would on the other hand add some magic that can cause confusion.

**Comment by elado** [comment]
But that's what it all about, being unobtrusive to your code, so delegation is a must.
jQuery's version works with live events.

Anyway, I fixed some bugs (like assigning csrf token on a Request.Rails from a link)
and added support for delegation and bubbling of ajax events, so you can do:

`document.addEvent('ajaxComplete:relay(form)', ...`

Since MooTool's pseudo events syntax contains a colon, I had to add camelCase version for all 'ajax:' events (so both ajax:complete and ajaxComplete are fired, but only ajaxComplete bubbles).

I will release it soon, just testing it on a project of mine.

_If someone got here from google or something, and interested in my fix before I release it, feel free to contact directly elad@ossadon.com_
